[package]
name = "switchd"
version = "0.1.0"
edition = "2021"
description = "MT7531 Gigabit Switch driver"

[dependencies]
userlib = { path = "../../userlib" }
abi = { path = "../../abi" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
