[package]
name = "xhcid"
version = "0.1.0"
edition = "2021"
description = "xHCI USB host controller driver"

[dependencies]
userlib = { path = "../../userlib" }
usb = { path = "../usb" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
