[package]
name = "partd"
version = "0.1.0"
edition = "2024"
description = "Partition table driver"

[dependencies]
userlib = { path = "../../userlib" }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
