[package]
name = "wifid3"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = { path = "../../userlib" }
pcie = { path = "../pcie" }
mt7996 = { path = "../mt7996" }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
