[package]
name = "fatfsd"
version = "0.1.0"
edition = "2024"
description = "FAT filesystem driver"

[dependencies]
userlib = { path = "../../userlib" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
