[package]
name = "vfsd"
version = "0.1.0"
edition = "2024"
description = "Virtual filesystem daemon"

[dependencies]
userlib = { path = "../../userlib" }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
