[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

# For running unit tests on host, use ./test.sh
# (temporarily disables this config to use native target)
